"""empty message

Revision ID: 63b4340ef156
Revises: 690d1c3fe3ab
Create Date: 2024-03-17 12:49:49.250833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b4340ef156'
down_revision = '690d1c3fe3ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Movie', schema=None) as batch_op:
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
